# Generated by Django 4.1.13 on 2024-04-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='prices',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='types',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_type',
            field=models.TextField(null=True),
        ),
    ]
