# Generated by Django 4.1.13 on 2024-04-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_digital_remove_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prices',
        ),
        migrations.RemoveField(
            model_name='product',
            name='types',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_type',
        ),
        migrations.AddField(
            model_name='product',
            name='digital',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
