# Generated by Django 4.1.13 on 2024-04-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_product_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
