# Generated by Django 4.1.13 on 2024-04-21 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='weight',
            new_name='weight_class',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zipcode',
            new_name='pincode',
        ),
    ]
