# Generated by Django 4.1.13 on 2024-04-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_weight_product_weight_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight_class',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
