# Generated by Django 4.1.13 on 2024-04-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_weight_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight_class',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
